### ISSUE TITLE
App shows a white screen

### ISSUE THREAD

**Issue by Ternoc** [YunoHost-Apps/grr_ynh#1]
### Describe the bug

When logged with yunohost, grr display a white screen. No html is returned.
<img width="494" alt="Capture d’écran 2021-11-14 à 11 52 51" src="https://user-images.githubusercontent.com/11840322/141677940-89410b54-e25a-4a58-b98d-3527bb434d82.png">

### Context

- Hardware: VPS
- YunoHost version: 4.3.2.2
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch:

### Steps to reproduce

Access to grr app after logging in yunohost

### Expected behavior

Supposed to show the app.

**Comment by sebmennetrier** [comment]
Hi @Ternoc

I seems to be a bug of GRR about support of IPV6. Please, can you confirm that you access your server through ipv6 ?

If yes, a release that fix the issue should be available soon at GRR (about 2 weeks :crossed_fingers:, cf: [pre-release v3.4.3RC0](https://github.com/JeromeDevome/GRR/releases/tag/v3.4.3RC0)) and so the yunohost recipe will be updated with this new version.

**Comment by Ternoc** [comment]
Yes, disabling ipv6 resolved the problem.

**Comment by Sebseb01** [comment]
Hello, 

Thanks for your work.

I havve just installed this package on my Yunohost, and i have again this bug.  Have you planned an update ?

Thanks in advance

**Comment by sebmennetrier** [comment]
Hello @Sebseb01,

I just updated recipe to install last version of GRR.

Please let me known if the bug is fixed on your side :wink:
